### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by dayanare** [lilifernandez91/modulo-3-evaluacion-intermedia-lilifernandez91#1]
Buen trabajo @lilifernandez91  !

### Algunas pistas para acabarlo:

- [x] Comprueba que los inputs tengan algún valor cuando vas a añadir una nueva frase.
- [x] Resetea el estado de tu formulario cuando agregues  una nueva frase

Muy buen trabajo

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by lilifernandez91** [comment]
Hola profe, he solucionado las issues e hice otras mejoras para que el código fuera más legible. Quedo atenta a las recomendaciones. Gracias.
